### ISSUE TITLE
Can not proper transition between forward syncing and backwards syncing

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/tlbc-monitor#52]
The transition between forward syncing and backwards syncing is not properly handled and could result in an endless loop. If the backwards sync take to long, we will fall back to the forward sync, which will then erase the progress of the backwards sync, so we could alternate between the two forever.

**Comment by jannikluhn** [comment]
How about we just drop forward sync altogether and just accept an incomplete history? We might need to make some adjustments here and there but I'd guess it would be a net simplification. In practice this shouldn't make a difference at all as the monitor should be running continuously anyways and we've got rid of the initial full sync already.

**Comment by berndbohmeier** [comment]
I like the fact that you can analyze offline reporters in the past so I would not drop the forward sync unless we have a new solution for this.

**Comment by jannikluhn** [comment]
> I like the fact that you can analyze offline reporters in the past

Arguably that's a bad thing though as you'd potentially report validators as offline even though they've just been on the wrong side of a fork or censorship attack. I guess you're basically relying on an honest majority assumption during the time you're offline and the output of the monitor doesn't make this clear.

But since the bug is fixed now and it's only a minor issue that can be compensated with communication I'm ok with the status quo.

**Comment by berndbohmeier** [comment]
> been on the wrong side of a fork or censorship attack

They are effectively offline. You are just not able to proof if it is there fault or not. Doing that in realtime will only change it slightly for the censor case.
