### ISSUE TITLE
Script to remove a validator

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/tlbc-monitor#57]
included in the docker image of tlbc-monitor

**Comment by weilbith** [comment]
Printing bytes into the equivocation log files was a horrible idea. Hex-Strings are much better and easier to handle. The problem is to have a String which is a `byte` representation by _Python_ to become `byte`s again without become parsed again. Since I don't see any advantage in logging the `byte` representation, I'll open an issue to adjust this.

**Comment by weilbith** [comment]
Done by PR #65 and #66
